# Generated by Django 6.0 on 2025-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(help_text='URL or path (e.g., /about or https://example.com)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Important Link',
                'verbose_name_plural': 'Important Links',
                'db_table': 'important_links',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Golden Section', max_length=200)),
                ('site_tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=20)),
                ('default_whatsapp', models.CharField(help_text='Default WhatsApp number with country code (e.g., +447123456789)', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('footer_description', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© 2025 Golden Section. All rights reserved.', max_length=200)),
                ('business_hours', models.TextField(blank=True, help_text='Business hours in JSON format: {"Monday": "9:00 AM - 5:00 PM", ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
                'db_table': 'site_configuration',
            },
        ),
    ]
