# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_country_code',
            field=models.CharField(default='971', help_text='Default country code for phone numbers (e.g., 971 for UAE, 880 for Bangladesh)', max_length=10),
        ),
    ]
