# Generated by Django 6.0 on 2025-12-13 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_siteconfiguration_default_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='business_hours',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Business hours in JSON format: {"Monday": "9:00 AM - 5:00 PM", ...}'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
