# Generated by Django 6.0 on 2025-12-11 07:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='business_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Business logo (optimized automatically)', null=True, upload_to='providers/logos/'),
        ),
        migrations.AlterField(
            model_name='providergallery',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Gallery image (optimized automatically)', upload_to='providers/gallery/'),
        ),
    ]
