# Generated by Django 6.0 on 2025-12-13 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_business_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
