# Generated by Django 6.0 on 2025-12-10 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='services/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional image URLs')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Service-specific WhatsApp. Leave empty to use category/default WhatsApp.', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_popular', models.BooleanField(default=False, help_text='Show in popular section')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='categories.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='categories.subcategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
                'db_table': 'service_gallery',
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('name', models.CharField(help_text='e.g., "Basic Package"', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in GBP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features included in this tier')),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False, help_text='Highlight as recommended')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Pricing Tier',
                'verbose_name_plural': 'Service Pricing Tiers',
                'db_table': 'service_pricing_tiers',
                'ordering': ['service', 'order', 'tier_type'],
                'unique_together': {('service', 'tier_type')},
            },
        ),
    ]
