# Generated by Django 6.0 on 2025-12-10 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Service rating (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
