# Generated by Django 5.2.6 on 2025-12-11 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicepricingtier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicepricingtier',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='gallery_images',
        ),
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(default='', help_text='Detailed overview of the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_provided',
            field=models.IntegerField(default=0, help_text='Total services completed'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average service rating (0.0 - 5.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times viewed'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/additional/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='services.service')),
            ],
            options={
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
                'db_table': 'service_additional_images',
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week')),
                ('opening_time', models.TimeField(blank=True, help_text='Opening time (e.g., 09:30 AM)', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Closing time (e.g., 07:00 PM)', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Check if closed on this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='services.service')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'db_table': 'service_business_hours',
                'ordering': ['service', 'weekday'],
                'unique_together': {('service', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
            options={
                'verbose_name': 'Service FAQ',
                'verbose_name_plural': 'Service FAQs',
                'db_table': 'service_faqs',
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Free Consultation, 24/7 Support', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('icon', models.CharField(blank=True, help_text='Icon class (e.g., feather-check, ti-shield-check)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Include',
                'verbose_name_plural': 'Service Includes',
                'db_table': 'service_includes',
                'ordering': ['service', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Fan Repair, AC Installation', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class (e.g., feather-fan, ti-air-conditioning)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Sub Service',
                'verbose_name_plural': 'Sub Services',
                'db_table': 'service_sub_services',
                'ordering': ['service', 'order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceGallery',
        ),
        migrations.DeleteModel(
            name='ServicePricingTier',
        ),
    ]
