# Generated by Django 6.0 on 2025-12-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0003_alter_servicepricingtier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Service provider', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to='providers.provider'),
        ),
    ]
