# Generated by Django 6.0 on 2025-12-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for image (for accessibility)', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for featured image (for accessibility)', max_length=200),
        ),
        migrations.AddField(
            model_name='subservice',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for image (for accessibility)', max_length=200),
        ),
        migrations.AddField(
            model_name='subservice',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Sub-service image', null=True, upload_to='services/sub_services/'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for this sub-service', max_digits=10),
        ),
    ]
