# Generated by Django 6.0 on 2025-12-11 07:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_additionalimage_alt_text_service_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Additional service image (optimized automatically)', upload_to='services/additional/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Main service image (optimized automatically)', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Sub-service image (optimized automatically)', null=True, upload_to='services/sub_services/'),
        ),
    ]
