# Generated by Django 6.0 on 2025-12-13 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_additionalimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='overview',
            field=ckeditor.fields.RichTextField(default='', help_text='Detailed overview of the service'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='serviceinclude',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional detailed description'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
