# Generated by Django 6.0 on 2025-12-11 07:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Category icon (optimized automatically)', null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Category banner image (optimized automatically)', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Subcategory icon (optimized automatically)', null=True, upload_to='subcategories/icons/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Subcategory banner image (optimized automatically)', null=True, upload_to='subcategories/'),
        ),
    ]
