# Generated by Django 6.0 on 2025-12-11 07:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Blog featured image (optimized automatically)', upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Customer photo (optimized automatically)', null=True, upload_to='testimonials/'),
        ),
    ]
