# Generated by Django 6.0 on 2025-12-11 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_alter_provider_business_logo_and_more'),
        ('services', '0006_alter_additionalimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(help_text='Customer first name', max_length=100)),
                ('customer_last_name', models.CharField(help_text='Customer last name', max_length=100)),
                ('customer_email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+971501234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('location_latitude', models.DecimalField(decimal_places=6, help_text='Service location latitude', max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=6, help_text='Service location longitude', max_digits=9)),
                ('location_address', models.TextField(help_text='Full service location address')),
                ('appointment_date', models.DateField(help_text='Scheduled appointment date')),
                ('appointment_time', models.CharField(help_text='Scheduled appointment time (e.g., 10:00 AM)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Booking status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special instructions')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('whatsapp_sent', models.BooleanField(default=False, help_text='WhatsApp notification sent')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, help_text='WhatsApp sent timestamp', null=True)),
                ('whatsapp_number_used', models.CharField(blank=True, help_text='WhatsApp number used for notification', max_length=20)),
                ('booking_reference', models.CharField(editable=False, help_text='Unique booking reference number', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Service provider', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='providers.provider')),
                ('service', models.ForeignKey(help_text='Main service booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('sub_services', models.ManyToManyField(blank=True, help_text='Selected sub-services', related_name='bookings', to='services.subservice')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
