# Generated by Django 6.0 on 2025-12-13 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='admin_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_address',
            field=ckeditor.fields.RichTextField(help_text='Full service location address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional notes or special instructions'),
        ),
    ]
