# Generated by Django 6.0 on 2025-12-10 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pricing_tier', models.CharField(blank=True, help_text='basic, standard, or premium', max_length=20)),
                ('booking_estimate', models.CharField(help_text='e.g., "2-3 Hrs", "1 Day"', max_length=50)),
                ('booking_datetime', models.DateTimeField(help_text='Preferred date and time')),
                ('number_of_people', models.IntegerField(default=1)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collection_address', models.TextField()),
                ('collection_postal_code', models.CharField(max_length=20)),
                ('collection_city', models.CharField(max_length=100)),
                ('collection_property_type', models.CharField(choices=[('house', 'House'), ('flat', 'Flat/Apartment'), ('business', 'Business'), ('other', 'Other')], default='house', max_length=50)),
                ('collection_bedrooms', models.IntegerField(default=0)),
                ('collection_floor_level', models.CharField(blank=True, max_length=50)),
                ('collection_has_lift', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_property_type', models.CharField(blank=True, choices=[('house', 'House'), ('flat', 'Flat/Apartment'), ('business', 'Business'), ('other', 'Other')], max_length=50)),
                ('delivery_bedrooms', models.IntegerField(default=0)),
                ('delivery_floor_level', models.CharField(blank=True, max_length=50)),
                ('delivery_has_lift', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('cc_zone', models.BooleanField(default=False, help_text='Congestion Charge Zone')),
                ('booking_charges', models.DecimalField(decimal_places=2, default=42.0, max_digits=10)),
                ('cc_zone_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_number_used', models.CharField(blank=True, max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotations/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations.servicerequest')),
            ],
            options={
                'verbose_name': 'Request Attachment',
                'verbose_name_plural': 'Request Attachments',
                'db_table': 'request_attachments',
                'ordering': ['request', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown', models.TextField(help_text='Price breakdown details')),
                ('estimated_duration', models.CharField(max_length=100)),
                ('terms_conditions', models.TextField(blank=True)),
                ('valid_until', models.DateTimeField(help_text='Quotation valid until')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_quotations', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.servicerequest')),
            ],
            options={
                'verbose_name': 'Quotation Response',
                'verbose_name_plural': 'Quotation Responses',
                'db_table': 'quotation_responses',
                'ordering': ['-sent_at'],
            },
        ),
    ]
