# Generated by Django 6.0 on 2025-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_bedrooms',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_city',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_floor_level',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_has_lift',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_postal_code',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='collection_property_type',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_bedrooms',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_floor_level',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_has_lift',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_postal_code',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='delivery_property_type',
        ),
    ]
