# Generated by Django 6.0 on 2025-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_remove_servicerequest_collection_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='booking_date',
            field=models.DateField(blank=True, help_text='Appointment date', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='booking_time',
            field=models.TimeField(blank=True, help_text='Appointment time', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location_address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, help_text='Preferred date and time', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_estimate',
            field=models.CharField(blank=True, help_text='e.g., "2-3 Hrs", "1 Day"', max_length=50),
        ),
    ]
