# Generated by Django 5.2.6 on 2025-12-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_servicerequest_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_datetime',
            field=models.DateTimeField(blank=True, help_text='Combined date and time', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='booking_time',
            field=models.CharField(blank=True, help_text='Appointment time (e.g., 9:00 AM)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='number_of_people',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
