# Generated by Django 6.0 on 2025-12-13 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_update_booking_time_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationresponse',
            name='breakdown',
            field=ckeditor.fields.RichTextField(help_text='Price breakdown details'),
        ),
        migrations.AlterField(
            model_name='quotationresponse',
            name='terms_conditions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='admin_notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location_address',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full address'),
        ),
    ]
